[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = 'source ~/.vim/rc/plugin/startify.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_source = '''
set background=dark
colorscheme iceberg
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
if !has('gui')
    let g:indent_guides_auto_colors = 0
    hi IndentGuidesOdd  ctermbg=DarkGray
    hi IndentGuidesEven ctermbg=Gray
endif
'''

[[plugins]]
repo = 'mattn/vim-textobj-url'
depends = 'vim-textobj-user'
on_source = 'vim-textobj-user'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_source = 'source ~/.vim/rc/plugin/lightline.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTreeToggle'
hook_add = '''
nnoremap [nerd] <Nop>
nmap <Space>f [nerd]
nnoremap <silent>[nerd]t :<C-u>NERDTreeToggle<CR>
nnoremap <silent>[nerd]f :<C-u>NERDTreeFocus<CR>
nnoremap <silent>[nerd]j :<C-u>NERDTreeCWD<CR>
nnoremap <silent>[nerd]c :<C-u>NERDTreeClose<CR>
nnoremap <silent>[nerd]x :<C-u>NERDTreeClose<CR>
'''
hook_source = '''
let g:NERDTreeDirArrowExpandable = '+'
let g:NERDTreeDirArrowCollapsible = '-'
let g:NERDTreeShowBookmarks = 1
'''

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
set ve=onemore
'''

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'kana/vim-submode'
hook_source = 'source ~/.vim/rc/plugin/submode.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
hook_add = '''
source ~/.vim/rc/plugin/markdown.vim
'''

[[plugins]]
repo = 'thinca/vim-ft-diff_fold'

[[plugins]]
repo = 'thinca/vim-ft-help_fold'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'tmhedberg/matchit'

[[plugins]]
repo = 'Shougo/vimproc'
hook_post_update = '''
if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
elseif executable('gmake')
    let cmd = 'gmake'
else
    let cmd = 'make'
endif
let g:dein#plugin.build = cmd
'''
